### PR TITLE
finished Test1.txt

### PR DESCRIPTION
**Pull request by CrazyDevo**

### CODE REVIEW

**Review by SumeyraOzgun — APPROVED** [review]
Good job!

**Review by Waniusha15 — APPROVED** [review]
great job

**Review by chadid1 — APPROVED** [review]
great job

**Review by Cesur-gith — APPROVED** [review]
Well done!

**Review by Tugbabaki — CHANGES_REQUESTED** [review]
looks great! Only thing is please add "ed" after finish

**Review by Tugbabaki — APPROVED** [review]

**Pull request merged**
